name: Java CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build WAR
      run: ./gradlew bootWar
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: build/libs/gradle-spring-boot-demo.war
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, package]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: package
    - name: Deploy to ElasticBeanstalk
      uses: einaregilsson/beanstalk-deploy@v6
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: gradle-spring-boot
        environment_name: dev-env
        version_label: gradle-spring-boot-${{ github.run_id }}
        region: us-east-2
        deployment_package: package/gradle-spring-boot-demo.war
